### ISSUE TITLE
TypeError importing from KOReader vocab builder

### ISSUE THREAD

**Issue by daniesteban** [FreeLanguageTools/vocabsieve#101]
**Describe the bug**
When importing words from KOReader vocab builder a window titled _Something went wrong_ shows the error message _Error: TypeError('expected str, bytes or os.PathLike object, not NoneType')_ 

**To Reproduce**
1. Go to Import -> KOReader vocab builder
2. Navigate to folder containing books on KOreader. In this point I'm not sure if I doing it correctly. My books are arranged in subfolders in a folder named _documents_ in root path. So I just select documents folder. I'm not sure if there's any koreader configuration in this folder.
3. When open the error windows appear and nothing is imported

**Expected behavior**
Import the words saved in the koreader vocabulary builder

**Desktop:**
 - OS: Debian trixie (testing)
- Vocabsieve version: VocabSieve-v0.10.2-linux-amd64 in snap format (.AppImage)

**Additional context**
I'm importing KOreader data from a Kindle (jailbreak) with KUAL + KOreader. Tried connected both USB and SSH

**Comment by 1over137** [comment]
Are the languages in your books set correctly?
VocabSieve filters books to only show books in your target language, but some books have bad metadata.
That kind of error usually indicates failure to detect any books.

If that still doesn't work, does it work if you copy the whole directory containing books over?
