### ISSUE TITLE
Web Reader Integration with mp3 Audiobook

### ISSUE THREAD

**Issue by Cloufish** [FreeLanguageTools/vocabsieve#108]
**Is your feature request related to a problem? Please describe.**

It's not really a problem, because existing free workflows do exist
You can Transcribe the Audiobook, with `pyTranscriber.py`, open it with `mpvacious` and have an e-book reader next to the windows, like this:
![image](https://github.com/FreeLanguageTools/vocabsieve/assets/32965886/1be01919-b43f-40a6-8484-55feab4a1b5f)

**Describe the solution you'd like**
But it would be really nice, to have this in one Web Browser Windows, and have more smooth process of sentence mining with  books, that produce flashcards with audiobook audio

**Also**, as seen in the screenshot above, `pyTranscriber` doesn't perform ideal transcription. It would be great If the e-book was the main source of mined sentence, and the transcription itself would be only to set timings.

**Additional context**
What are the obstacles to implement this feature?
Do you need help with anything?
I'm not a programmer, just a tech-savvy language learner, but willing to help.

**Comment by 1over137** [comment]
Don't transcribe, just use `aeneas` to align the text and the audio and use it in mpvacious.
https://github.com/readbeyond/aeneas
Or use Whisper which may be good enough in many languages. I don't really think there is a lot to be gained here, and I don't really plan on implementing an audio player thing unless I'm also implementing a video player, which is unlikely.
