### ISSUE TITLE
Cant change a verb to the infinitiv

### ISSUE THREAD

**Issue by JunkMeal** [FreeLanguageTools/vocabsieve#114]
**Is your feature request related to a problem? Please describe.**
So when I am mining german for example the verb gegeben. Which is a Partizip Perfekt of geben I want the word that I am mining to change to geben. But It seems that I can't do that

**Describe the solution you'd like**
![image](https://github.com/FreeLanguageTools/vocabsieve/assets/65283415/9694346e-3c5a-44e7-a4a8-a2e6e1254945)
Maybe make it so I can change the word here.

**Additional context**
The Migaku dictionaries have a conjugations.json file which might help

**Comment by artjomsR** [comment]
Not sure I understand. You say that you cannot change the word but you have `geben` in the Word field (which is changed from `gegeben`). You should be able to save (Ctrl+S) the note after that, which would put `geben` from the Word field into your newly created note

**Comment by JunkMeal** [comment]
Yeah but the definition doesn't change and I like to review it before making a card

**Comment by 1over137** [comment]
What do you want to change? If you mean the text on the bottom of the definition text box, then that's only to signify the source of the definition. It does not go to your Anki card. Just changing the word field would suffice.

**Comment by JunkMeal** [comment]
![image](https://github.com/FreeLanguageTools/vocabsieve/assets/65283415/b4054e41-9dac-4cb2-aa5a-889d5fb51073)
When I change the word field the definition is still for (adj) gegeben and not for (verb) geben
![image](https://github.com/FreeLanguageTools/vocabsieve/assets/65283415/9ca1473b-045d-4f9a-b260-70bbb3afd4b5)
and when I add it to anki the definition is still wrong

**Comment by 1over137** [comment]
In that case, you want to use define direct. Although the button is gone you can still access it by selecting the word and pressing Shift+Ctrl+D

**Comment by JunkMeal** [comment]
Uhm if i select the word "geben" in the word field and press shift+ctrl+d it switches it back to gegeben
