### ISSUE TITLE
Sometimes notes are created, sometimes not

### ISSUE THREAD

**Issue by HadIKnown** [FreeLanguageTools/vocabsieve#115]
**Describe the bug**
For every 10 words or so, I am able to create a note, verified by the fields on VocabSieve clearing and checking on Anki. More often than not, no note is created. I click the create note button or Cmd + S and the button highlights, but then leaves the word, sentence, and definition fields filled with the note contents, meaning no note was created. 

EDIT: Looks like the issue is in the definition... I can't use the autopopulated definition from either of the dictionaries I've downloaded for Turkish. If I replace the definition with something else, it works fine.
 
**To Reproduce**
1. Go to Turkish content, in asbplayer or Wikipedia, for example.
2. Paste content into sentence field (or auto-fill sentence)
4. Define a word in the sentence.
5. Click create note. 
6. See error

**Expected behavior**
A note to be created in Anki, or if no note can be created, explain why. Sometimes, I try to add a note that already exists, and the app tells me that. EDIT: I shouldn't have to alter the auto-populated definition for the note to be accepted.

**Desktop (please complete the following information):**
 - OS: MacOS Bir Sur 11.7
- Vocabsieve version (if nightly, must be latest): v0.10.2

**Comment by 1over137** [comment]
Check if this is reproducible in 0.11. If so, post a log here.

**Comment by HadIKnown** [comment]
Well, this issue seems fixed, but now the configuration button at the bottom of the window is gone, so I can't select which local dictionaries I want to use :(

![Ekran Resmi 2023-12-29 ÖS 2 50 03](https://github.com/FreeLanguageTools/vocabsieve/assets/17707797/be27e5ee-53c9-4c5b-a122-4e7fbbcf5982)

**Comment by artjomsR** [comment]
Config menu should be accessible as a menu item (ie at the top of the screen if you're on a mac)

**Comment by HadIKnown** [comment]
I already checked there, and I just checked again, there's nothing in the
top bar.

Best,

Yeshar Ivan Hadi


1over137 ***@***.***>, 29 Ara 2023 Cum, 17:36 tarihinde şunu
yazdı:
