### ISSUE TITLE
VocabSieve auto close immediately after running

### ISSUE THREAD

**Issue by BEST8OY** [FreeLanguageTools/vocabsieve#118]
**Describe the bug**
VocabSieve auto close immediately after running (it doesn't show anything, but I see it for a brief moment in task manager)

**To Reproduce**
1. Loaded a mdx file ( 550mb)
2. Software not responding.
3. Force close by ending task
4. vocabsieve not running anymore
5. .msi uninstallation + deleting "AppData\Local\FreeLanguageTools\VocabSieve" and installing it again didn't solve it

**Expected behavior**
It should run normally .

**Logs**
```
2023-12-30 11:30:51.328 | DEBUG    | vocabsieve.main:initSources:121 - Initializing sources
2023-12-30 11:30:51.329 | DEBUG    | vocabsieve.main:initSources:125 - Source Group 1: [] has been created.
2023-12-30 11:30:51.332 | DEBUG    | vocabsieve.main:initSources:138 - Source Group 2 is disabled, emptying source widget.
```

**Desktop (please complete the following information):**
 - OS:  Windows 11
- Vocabsieve version (if nightly, must be latest): 0.11.0

**Comment by 1over137** [comment]
Strange.. Is that all the log there is?
I think you should probably have waited a bit longer since big MDX files are going to take quite some time to import, but this still shouldn't be happening. I assume the config is corrupted somehow.
On Windows I assume the configs are stored in the registry. Try clearing everything in the following:
`HKEY_CURRENT_USER\Software\FreeLanguageTools\VocabSieve`

**Comment by BEST8OY** [comment]
> Strange.. Is that all the log there is? I think you should probably have waited a bit longer since big MDX files are going to take quite some time to import, but this still shouldn't be happening. I assume the config is corrupted somehow. On Windows I assume the configs are stored in the registry. Try clearing everything in the following: `HKEY_CURRENT_USER\Software\FreeLanguageTools\VocabSieve`

Yes that's all there is to it.
I sent the MDX file in telegram for you.
I deleted the reg directory and now it runs fine.

I believe there should be a progress bar or a fails safe measure (in case someone got impatient (like me 🙂) and force closed  VocabSieve) to prevent the corruption of reg configs!

**Comment by 1over137** [comment]
Can't reproduce, the dictionary imported just fine, though it did take several minutes. I also see no reason why that should lead to a registry corruption. Maybe I should include some mechanism to show progress though, especially with the slower formats.
