### ISSUE TITLE
[Feature Request] Add support for .zim files

### ISSUE THREAD

**Issue by ghost** [FreeLanguageTools/vocabsieve#12]
Maybe just “wishful thinking” or daydreaming: Wiktionaries in .zim format would be very useful for "vocabsieve" users.

https://en.wikipedia.org/wiki/ZIM_(file_format)

.zim files can be obtained here:
https://wiki.kiwix.org/wiki/Content_in_all_languages

and also: http://library.kiwix.org/

**Comment by 1over137** [comment]
zim support sounds feasible
will be added either next release, or when mdict is sorted out.

**Comment by 1over137** [comment]
With parsed Wiktionary content being supported now and zim being poorly displayed on vocabsieve, I think there is not much purpose to doing this.
