### ISSUE TITLE
Add simple lemmatization tweaks

### ISSUE THREAD

**Issue by Mycheze** [FreeLanguageTools/vocabsieve#121]
**Is your feature request related to a problem? Please describe.**

There are many "simple" lemmatizations that Vocabsieve doesn't find. The most common example for me (in Czech) is the colloquial -ej ending. It's a very common thing in certain dialects, but it's non-standard and doesn't appear in dictionaries. It's very annoying to have to go and change the -ej ending for -ý, look up the word with a double click, then to back and reverse the change for the actual Anki card. 

**Describe the solution you'd like**

Some way to add additional "lemmatization" steps in the language config. I would love to say (somehow) "for words that end in -ej, if there's no definition found, try looking them up with -ý instead. 

**Additional context**
![2023-12-30_12-28_1](https://github.com/FreeLanguageTools/vocabsieve/assets/71797685/0a638a3d-b8e5-43be-a43b-bf8428098fa7)
![2023-12-30_12-28](https://github.com/FreeLanguageTools/vocabsieve/assets/71797685/804a893e-a91d-4109-bdeb-6320543f408b)
This is a common thing in Czech: [link](https://cs.wikipedia.org/wiki/%C4%8Cesk%C3%A1_n%C3%A1%C5%99e%C4%8Dn%C3%AD_skupina)

**Comment by 1over137** [comment]
What if I implement some way to use custom regular expressions as a fallback lemmatizer?
This will probably involve a series of textboxes of regular expression replacements.
It's not the most user-friendly way to do things but a better solution will take much longer

**Comment by 1over137** [comment]
![image](https://github.com/FreeLanguageTools/vocabsieve/assets/22680475/b561d281-0f3f-4bdb-bb54-a44df849712e)
This is implemented as a simple regex replacement for now.

**Comment by Mycheze** [comment]
This is the greatest day of my life 🙏🙇
