### ISSUE TITLE
Fails to start because QApplication is not instantiated before qdarktheme is imported

### ISSUE THREAD

**Issue by yuki-tsubaki** [FreeLanguageTools/vocabsieve#123]
**Describe the bug**
The application doesn't start because `qtdarktheme.setup_theme("auto")` (in `qdarktheme`) is called before `QApplication` is instantiated. The program doesn't start (and gives the backtrace I will give in the 'Additional context' section (I don't know where else to put it with this template)). 

It is resolved when I switch the import order (details in the 'Fix' section).

**To Reproduce**
1. Install Vocabsieve 0.11.0
2. Run Vocabsieve

**Expected behavior**
I expect the program to start :>

**Screenshots**
N.A.

**Logs**
Irrelevant as the program wasn't even starting. See the backtrace in the 'Additional context' section.

**Desktop:**
- OS: Arch Linux (also tested on Manjaro)
- Vocabsieve version (if nightly, must be latest): 0.11.0-00 (from AUR package)
- `qdarktheme`: 2.1.0-3 (from AUR package)

**Additional context**
Here is the backtrace that I get:

```
pymorphy3 is available for RU
pymorphy3 is available for UK
Traceback (most recent call last):
  File "/usr/bin/vocabsieve", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/vocabsieve/main.py", line 864, in main
    qdarktheme.setup_theme("auto")
  File "/usr/lib/python3.11/site-packages/qdarktheme/_main.py", line 160, in setup_theme
    raise Exception("setup_theme() must be called after instantiation of QApplication.")
Exception: setup_theme() must be called after instantiation of QApplication.
```

**Fix**
Luckily, this seems like it is easily fixed by changing the order of the imports in `main.py` so that `app` is initialized before `qdarktheme` is imported (assuming my fix isn't messing anything else up (I don't know because I've never used it before so I don't know how well it usually works)).

To fix it I simply moved the `import qdarktheme` from its current position (main.py:12) to immediatly after the import of `app` from `.global_names` (currently main.py:22 with the comment "First local import").

After doing this the program starts and runs properly (at least as far as I can tell). There are some UI issues but I don't know if they are a result of my fix or would be there anyway.

Here is a screenshot of one (dropdown boxes backgrounds are missing):

![potential-issue](https://github.com/FreeLanguageTools/vocabsieve/assets/72632494/cc5ed09b-e811-4bd4-b8d0-29ed3630b639)

**Comment by 1over137** [comment]
I thought this has to do with qdarktheme trying to use PyQt6/PySide6 if your system has it instead of PyQt5. I should check if your fix would work.

**Comment by yuki-tsubaki** [comment]
@1over137 I was helping install it for a family member so I can't check the Manjaro machine, but at least on mine, I have both PyQt6 and PyQt5 installed.

Unless `qdarktheme` is doing something weird when selecting which one to use I would assume that that part is being handled correctly (I haven't looked into it too deeply so far, though).

Given the order switching makes the app sucessfully start and the exception message warning that "setup_theme() must be called after instantiation of QApplication" it seems like that is at least part of the original problem.

If you are referring to the dropdown-box UI messiness that was there after I got it to start, then I wouldn't be surprised if that were the cause.

**Comment by yuki-tsubaki** [comment]
As an update on the dropdown box thing/UI after the 'fix':
The theming situation seems much better on my personal computer (the more plain/custom Arch one) than they were on the Manjaro one I sent the first screenshot from. The dropdown-box appears better, but is infact still transparent (the blur from my compositor just happens to make it readable in this case).

My Computer:
![interface-on-mine](https://github.com/FreeLanguageTools/vocabsieve/assets/72632494/a364f060-e2a2-40eb-b0f1-a310aedcac98)

Manjaro (family member's computer with basically default config):

![manjaro-issue](https://github.com/FreeLanguageTools/vocabsieve/assets/72632494/a9cfd846-d933-41ed-a162-503a2f3a0839)

**Summary of wierd things that I noticed (that the fix may or may not have caused)**
- On the manjaro the outer border of the dark theme version of the configuration pane remains white.
- On both, the dropdown-boxes have a transparent background (practically mitigated on mine because I had my compositor set to blur those anyway).

If this turns out to be unrelated I'll make a separate issue.

**Comment by 1over137** [comment]
What I observed:
- Looking at the source code of qdarktheme, it looks like importing PyQt5.QtCore first would solve the issue. I moved `import qdarktheme` to right before the .global_names import to see if it would work, and it appears to work just fine.
- The lack of background for the combobox appears to be unrelated to this specific change, however, but rather more likely due to some kind of bug in the stylesheet in qdarktheme. If PyQt6 or PySide6 isn't installed (like in a virtual environment or the appimage), this does not happen. However, I can't reproduce this in a virtual environment with both PyQt5 and PySide6 installed, which leads me to think that it's your system theme leaking through the qdarktheme stylesheet causing a bug. You can check this by using `QT_QPA_PLATFORMTHEME=qt5c python vocabsieve.py` (deliberate mistake to use default theme), and this issue does not occur. 

On another note, I am planning to move to PySide6 soon, which may or may not affect this.

In the mean time, you should probably let your family member use the AppImage, which is an isolated environment with only PyQt5.

**Comment by yuki-tsubaki** [comment]
Thanks I didn't even know there was an appimage version.

Yep, moving the import to where you said works just fine as well. (If you want I can close this issue and make a new one for the theming issues now that you confirmed that they are independent.)

On the background issue, your specific test doesn't work.

Both of the computers I tested use `kvantum` which is specified by the `QT_STYLE_OVERRIDE` variable instead of `QT_QPA_PLATFORMTHEME`. I was able to get the backgrounds to load using `QT_STYLE_OVERRIDE="" python vocabsieve.py`. (The fact that is seems to actually listen to the environment variables, unlike some other Qt apps which just seem to have broken themes regardless, is really nice).

Oddly enough, if I go in the preview of Kvantum to see what it should like with the system theme fully and properly applied, the combo boxes all have completely opaque backgrounds so whatever is going on here is an emergent behavior.

Kvantum preview showing opaque combobox background:
![kvantum-preview](https://github.com/FreeLanguageTools/vocabsieve/assets/72632494/66a36618-bbff-478e-93cf-5fed8b9820f9)

**Comment by 1over137** [comment]
> The fact that is seems to actually listen to the environment variables

This is just a result of it using system Qt libraries instead of statically linked ones, like in the appimage.

I actually plan to provide a way to use system default theme on Linux. This custom theme is applied mainly to solve the lack of dark theme on Windows and the general ugliness of the default theme, but I know a lot of Linux users would prefer it to respect the system theme, and maybe that can be the default on Linux since we have proper light/dark systemwide themes anyways.

**Comment by yuki-tsubaki** [comment]
> This is just a result of it using system Qt libraries instead of statically linked ones, like in the appimage.

Yea that would make sense. The example I was thinking of was KDE Connect which uses Qt libraries but needs a bunch of KDE specific config things to control the theming (rather than working like other Qt apps).

Mostly though, it was just a compliment for having a pretty straightforward app.

**Comment by Cloufish** [comment]
I can confirm that I have the similar issue

But I use Arch Linux btw,
I wanted to add Dark theme globally to my application. And It works perfectly for most applications, but not for vocabsieve

I've done this:
https://wiki.archlinux.org/title/Dark_mode_switching
![image](https://github.com/FreeLanguageTools/vocabsieve/assets/32965886/b9541006-c73f-49bb-9eb6-aee6c40af10f)
And only that.

```shell
$ vocabsieve
QApplication: invalid style override 'adwaita-dark' passed, ignoring it.
        Available styles: Windows, Fusion
pymorphy3 is available for RU
pymorphy3 is available for UK
Traceback (most recent call last):
  File "/usr/bin/vocabsieve", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/vocabsieve/main.py", line 862, in main
    qdarktheme.setup_theme(theme)
  File "/usr/lib/python3.11/site-packages/qdarktheme/_main.py", line 160, in setup_theme
    raise Exception("setup_theme() must be called after instantiation of QApplication.")
Exception: setup_theme() must be called after instantiation of QApplication.
```

**Comment by yuki-tsubaki** [comment]
@Cloufish Have you tried opening a different Qt application with that value for `QT_STYLE_OVERRIDE`? That error looks like it is a problem with your setup, not the specific application (but I could be wrong).

For example:
```bash
QT_STYLE_OVERRIDE="nonexistent" qalculate-qt

**Comment by 1over137** [comment]
https://github.com/FreeLanguageTools/vocabsieve/commit/7c3c3b56a0d36661ac33a966c6369f5e0638d14e adds an option to use the system theme, which is probably what most users on Linux actually want. You can sidestep this issue with that.

**Comment by Cloufish** [comment]
@yuki-tsubaki thanks

I've installed `adwaita-qt5-git` and the complaint about non-existing adwaita-dark disappears

My error now corresponds to your previous one.

```bash
pymorphy3 is available for RU
pymorphy3 is available for UK
Traceback (most recent call last):
  File "/usr/bin/vocabsieve", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/vocabsieve/main.py", line 862, in main
    qdarktheme.setup_theme(theme)
  File "/usr/lib/python3.11/site-packages/qdarktheme/_main.py", line 160, in setup_theme
    raise Exception("setup_theme() must be called after instantiation of QApplication.")
Exception: setup_theme() must be called after instantiation of QApplication.
```

**Comment by 1over137** [comment]
@Cloufish use the master version which contains the fix
The transparent background thing I'm assuming is a bug in qdarktheme.
