### ISSUE TITLE
Fails to launch due to AttributeError with qdarktheme module when installed using pip3 on python 3.12

### ISSUE THREAD

**Issue by DamienNB** [FreeLanguageTools/vocabsieve#137]
**Describe the bug**
vocabsieve installed on Fedora 39 now fails to launch.

**To Reproduce**
1. Run `pip3 install --user --upgrade --force-reinstall vocabsieve`
2. After installation is complete, attempt to start vocabsieve

**Expected behavior**
vocabsieve shouldn't fail to start

**Logs**
When trying to launch vocabsieve from the terminal, this is the output:
```
Traceback (most recent call last):
  File "/home/[username]/.local/bin/vocabsieve", line 5, in <module>
    from vocabsieve.main import main
  File "/home/[username]/.local/lib/python3.12/site-packages/vocabsieve/main.py", line 22, in <module>
    from .global_names import datapath, lock, app # First local import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/[username]/.local/lib/python3.12/site-packages/vocabsieve/global_names.py", line 40, in <module>
    qdarktheme.enable_hi_dpi()
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'qdarktheme' has no attribute 'enable_hi_dpi'
```

**Desktop (please complete the following information):**
 - OS: Fedora Workstation 39 x86_64
 - pip3 version: `pip-24.0-py3-none-any`
- Vocabsieve version (if nightly, must be latest): `vocabsieve-0.11.1-py3-none-any`

**Comment by 1over137** [comment]
I'll look into this. Do note that VocabSieve is currently tested with python 3.11. A lot of dependencies probably do not work for 3.12 yet. Either use a virtual environment with 3.11 or use the AppImage.

**Comment by 1over137** [comment]
0.12.4 adds support for python 3.12
