### ISSUE TITLE
[Feature Request] Support TSV and interaction with PyGlossary

### ISSUE THREAD

**Issue by GrimPixel** [FreeLanguageTools/vocabsieve#14]
TSV is the most lightweight method of storing dictionary data. [PyGlossary](https://github.com/ilius/pyglossary) can convert many type of data including TSV (Tabfile).

**Comment by 1over137** [comment]
I can support TSV and CSV. I can probably just copy a few files over from PyGlossary, like what I already did with stardict XDXF format. I don't really want to depend on it, though -- it seems rather too complicated and not that suitable as a library.

**Comment by 1over137** [comment]
@GrimPixel Can you provide me a sample TSV for the purpose of testing? It's a pretty simple file format, though I don't exactly know how they are supposed to look (which column is word, which column is definition, and if there are any extra columns)

**Comment by 1over137** [comment]
It's added now! Should be available by next release. The standard files I tested are the ones generated by pyglossary, i.e. first column is word, second column is definition. Definition can be in HTML or plaintext, but otherwise it may not display properly.

**Comment by GrimPixel** [comment]
Thank you  for your effort. I know some dictionaries that are written in TSV.
https://www.eki.ee/litsents/vaba/ies/eestiinglise.txt
https://gitlab.com/C0rn3j/NorwegianToEnglishDict/blob/master/4_finalDictionary/nb-NOtoENdictionary.txt
