### ISSUE TITLE
The "Bold selected word" setting was broken

### ISSUE THREAD

**Issue by voothi** [FreeLanguageTools/vocabsieve#148]
**Describe the bug**
In version 0.12.0 the "Bold selected word" setting was broken. I rolled back to 0.11.1. The screenshot shows the setting in the previous version 0.11.1. The new version has a checkbox instead of a selection list. The program does not respond to flag changes in version 0.12.0.

**To Reproduce**
Test
Settings (minimal after clear install)
Configure / Configure VocabSieve / General / Sources / Dictionary sources
Dictionary Group = Wiktionary (English)
Screenshot 2024-03-26 112629.png
<img width="524" alt="Screenshot 2024-03-26 112629" src="https://github.com/FreeLanguageTools/vocabsieve/assets/9587340/fc2fe9c4-ef14-4160-814d-40b9a958582e">
[2024 03 26 11 00 46 0:10 / 3:56](https://youtu.be/aLrzv069Z3g?t=10)

Case 1 (Default)
Configure / Configure VocabSieve / General
Bold selected word = enabled (by default)
Screenshot 2024-03-26 111148.png
<img width="526" alt="Screenshot 2024-03-26 111148" src="https://github.com/FreeLanguageTools/vocabsieve/assets/9587340/da6a4d38-ab33-4afd-9131-c76855481d6e">
[2024 03 26 11 00 46 0:42 / 3:56](https://youtu.be/aLrzv069Z3g?t=42)

Case 2
Configure / Configure VocabSieve / General
Bold selected word = disabled
Screenshot 2024-03-26 111108.png
<img width="539" alt="Screenshot 2024-03-26 111108" src="https://github.com/FreeLanguageTools/vocabsieve/assets/9587340/77143e75-4cb1-4c47-bcb8-c245023d2a59">
[2024 03 26 11 00 46 1:31 / 3:56](https://youtu.be/aLrzv069Z3g?t=91)

**Expected behavior**
As in version 0.11.1
photo_2024-03-26_11-31-59.jpg
![photo_2024-03-26_11-31-59](https://github.com/FreeLanguageTools/vocabsieve/assets/9587340/ec8c58fb-b7b0-408a-bc5a-88e8acf4c5d3)

**Screenshots**
Screenshots
Screenshot 2024-03-26 112629.png
Screenshot 2024-03-26 111148.png
Screenshot 2024-03-26 111108.png

Recording VocabSieve
2024-03-26 11-00-46.mkv
[2024 03 26 11 00 46](https://youtu.be/aLrzv069Z3g)

**Logs**
-

**Desktop (please complete the following information):**
- OS: Windows 11
- Vocabsieve version (if nightly, must be latest): 0.12.0

**Additional context**
Telegram thread:
"In version 0.12.0 the Bold word setting was broken."

**Comment by 1over137** [comment]
Fixed in 0.12.3
