### ISSUE TITLE
v 0.12.0 does not open on MacOS 14.4.1

### ISSUE THREAD

**Issue by Carl-in-Vermont** [FreeLanguageTools/vocabsieve#151]
**Describe the bug**
I have installed VocabSieve 0.12.0 using VocabSieve-v0.12.0-macos-arm64.dmg on a 2020 M1 Mac mini running MacOS 14.4.1. When I try to open the app, it appears on the dock, bounces, and stays on the dock. It does not open. No dot appears under it, and no window associated with the app appears. When I right-click on the icon in the dock and choose Open, the app bounces once but otherwise does nothing.  

v. 0.8.3 opens without a problem. 

Restarting the computer did not help. 

**To Reproduce**
This happens with v. 0.12.0 no matter whether I double click on the app (VocabSieve-v0.12.0-macos-arm64), highlight the app and chose command-O, right click on the app and choose Open, or use the open command in Terminal. 

Anki is installed, with Anki Connect. This issue occurs whether Anki is open or not.

**Expected behavior**
I expected the app to open and present the usual window. 

**Desktop (please complete the following information):**
 - OS: MacOS 14.4.1
- Vocabsieve version (if nightly, must be latest): 0.12.0

**Comment by juangf7** [comment]
@Carl-in-Vermont hope this helps: https://docs.freelanguagetools.org/installation.html#macos

**Comment by Carl-in-Vermont** [comment]
Apologies for omitting important information! I didn't mention in the original report that I _had_ run xattr on the app, before I reported the problem.  When I do that now, I get the following message:
xattr: /Applications/VocabSieve-v0.12.0-macos-arm64.app: No such xattr: com.apple.quarantine

**Comment by 1over137** [comment]
I assume something is wrong with the apple silicon build as it is on my own machine and signed ad-hoc. I'll probably need some help on this. In the mean time you should try to install the intel version of 0.12 which should still work as before.

**Comment by Carl-in-Vermont** [comment]
OK, I've now tried the Intel version of 0.12, and it won't open, either--before or after the xattr command. Interestingly, the first time I used the xattr command on it, Terminal did not return an error. The second time, the same "No such xattr: com.apple.quarantine" error came up. (It's possible that Terminal did not return an error the first time I used xattr on the ARM version, too.)
Anyway, v0.8.3 works on this machine. Is there any danger in using it?

**Comment by 1over137** [comment]
Yes, new versions can change the database in a way that would cause older ones to not work properly.
I suggest you reset all the data using 0.8.3 to return to a clean state and then run the 0.12 version again.

**Comment by 1over137** [comment]
if it still crashes, find the log file at 

Library/Application\ Support/FreeLanguageTools/VocabSieve/log/session-log-<date>-<time>.txt

Paste the content here.

**Comment by Carl-in-Vermont** [comment]
Resetting the data and settings worked. Thanks @1over137 !
