### ISSUE TITLE
2nd definition group initially not visible after lookup

### ISSUE THREAD

**Issue by artjomsR** [FreeLanguageTools/vocabsieve#154]
**Describe the bug**
After doing a lookup, the 2nd group always shows up as empty. If you go to the next definition (either by clicking the Next arrow or scrolling with the mouse wheel), then definitions appear again (starting from 2nd definition)

**To Reproduce**
1. Enable 2nd dictionary group in settings
2. Look up a word
3. Notice the 2nd group is empty. If you were to create a card now, the 2nd definition will be left blank!
4. Go to next definition in 2nd group
5. Notice that 2nd group has a definition now
6. Go to previous group and notice 1st definition is now available and visible

**Expected behavior**
2nd definition should be visible immediately after lookup

https://github.com/FreeLanguageTools/vocabsieve/assets/6875790/b4951d4a-5aa7-4150-b9eb-6d44f2f72dcd

**Desktop (please complete the following information):**
 - OS: Windows 10
- Vocabsieve version (if nightly, must be latest): `7073e356ec45323837ed996fbda6fb6f8d442147` seems to be the offending commit https://github.com/FreeLanguageTools/vocabsieve/commit/7073e356ec45323837ed996fbda6fb6f8d442147

**Comment by 1over137** [comment]
Can't reproduce this. Does this require that the first definition fail? It seems to work fine for me in c6bc86291cc93d221cda3082db2ae1de0a4e3df9

**Comment by artjomsR** [comment]
This is a strange one - I've fixed it locally by removing and readding the first (offending?) dictionary in the `Sources` tab. Now it works as expected. Closing for now
