### ISSUE TITLE
Offline Wiktionary Format

### ISSUE THREAD

**Issue by RameshKumarGogoi** [FreeLanguageTools/vocabsieve#16]
I am using English Wiktionary Exports [wikt-en-en-2018-10-07.7z](http://www.dictinfo.com/stardict/wikt-en-en-2018-10-07.7z).
But the format is different, so it is a little difficult to read.
Can you make it look similar to Online Wiktionary?
![image](https://user-images.githubusercontent.com/61318157/167565719-97e08252-940c-4adc-81d8-7989eef18fd1.png)
![image](https://user-images.githubusercontent.com/61318157/167565759-4ae9d205-0f69-4678-9562-2dea0c91a09f.png)

**Comment by 1over137** [comment]
By the way, check out [this page](https://wiki.freelanguagetools.org/vocabsieve_dicts) for resources you can download. There should be plenty of other dictionaries available for most other dictionaries. Note DSL is supported in your beta version.

**Comment by AboulFtouh** [comment]
thank you for the great work I want to use offline dictionary but the page you mentioned doesn't work, is there any other resourse to learn how to do it?

**Comment by 1over137** [comment]
If you mean the kaikki.org dump: It isn't supported yet, so it won't work
A new link to that resource page is here: https://docs.freelanguagetools.org/resources.html

**Comment by 1over137** [comment]
Implemented as support for files from kaikki.org, will be present in 0.12.
