### ISSUE TITLE
Errno 111

### ISSUE THREAD

**Issue by GrimPixel** [FreeLanguageTools/vocabsieve#17]
I don't want to use Anki when clicking on that “configure” button, so this thing popped up, twice:

<urlopen error [Errno 111] Connection refused>
AnkiConnect must be running to use the configuration tool.

**Comment by 1over137** [comment]
Hm, it shouldn't be popping up twice. Regardless, this is fixed on master now, and in next release it will show clearer instructions.

Something like this:
![20220512-170454](https://user-images.githubusercontent.com/22680475/168167897-457323e9-865d-4199-8ee3-a1f57d164dd1.png)
