### ISSUE TITLE
VocabSieve can't view external device for KOReader import

### ISSUE THREAD

**Issue by bee-san** [FreeLanguageTools/vocabsieve#172]
**Describe the bug**
I have a device (Boox Palma) plugged into my PC.

![image](https://github.com/user-attachments/assets/9317d147-831c-4e8b-a883-a2d27fcca47c)

I can see it in explorer and open it just fine.

VocabSieve cannot see this when I go to import koreader:
![image](https://github.com/user-attachments/assets/27b45ace-e202-40d8-9667-6d846eca913a)
![image](https://github.com/user-attachments/assets/2ff0bce1-f95d-49b6-bd0a-4c8c8d94bfb0)

But if I try to import via anything else, it does see it:
![image](https://github.com/user-attachments/assets/0a270f4f-4a70-48db-b5c1-c21d849a674b)
![image](https://github.com/user-attachments/assets/b66a33d0-c7a1-4ee3-a039-142cea54b4bf)

What's up with this?

**Desktop (please complete the following information):**
 - OS: Windows 11
- Vocabsieve version (if nightly, must be latest): v0.12.0

**Comment by 1over137** [comment]
This is probably more of a Windows problem. Is there a way for you to set it to be used as a storage device?
