### ISSUE TITLE
[MacOS]: Install app under the name "VocabSieve"

### ISSUE THREAD

**Issue by thelazyoxymoron** [FreeLanguageTools/vocabsieve#174]
Currently the app is installed under a specific version name i.e. `VocabSieve-v0.12.2-macos-arm64`. It should ideally be installed as `VocabSieve`.

<img width="304" alt="Screenshot 2024-09-30 at 2 57 28 PM" src="https://github.com/user-attachments/assets/0efa9807-7320-48d0-af17-b3dbd9680d72">

**Comment by v0ry** [comment]
Try this [Installation](https://docs.freelanguagetools.org/installation.html#macos)
You Should be able to change the name of the program with 
mv ~/path/to/application ~/new/path/to/application has to be in ~/Applications folder tho...

**Comment by 1over137** [comment]
https://github.com/FreeLanguageTools/vocabsieve/commit/110ebb706b9dcafecb749226dd5fba96374c0b5b
