### ISSUE TITLE
[Feature Request] Add option to detect duplicates

### ISSUE THREAD

**Issue by GPLv3-fan** [FreeLanguageTools/vocabsieve#18]
**Would it be possible to provide a visual feedback to a user whenever a duplicate is being created ?**

_For example, if a user wants to add the word "Cat" but it is already in Anki database, could VocabSieve detect that it is a duplicate and show a warning or confirmation window?_

Thanks for your great work !

**Comment by 1over137** [comment]
I'm fairly sure that AnkiConnect will throw an error if you try to create a duplicate card, based on first field of the note.

**Comment by artjomsR** [comment]
I think it would be good to have an option how duplicates should be treated. As you say, by default AnkiConnect will throw an error if you try to add a duplicate. I think it would be good to add a config to allow duplicate card creation. AnkiConnect supports it https://github.com/FooSoft/anki-connect/pull/99 , so one would need to add a global config and presumably pass that into `content` when it is created in https://github.com/FreeLanguageTools/vocabsieve/blob/master/vocabsieve/main.py#L850
