### ISSUE TITLE
app can't start on mac os x 12.4

### ISSUE THREAD

**Issue by vbalashi** [FreeLanguageTools/vocabsieve#23]
This is not a security issue: I allowed vocabsieve to be run, but it crashes after the start

**Comment by NSBum** [comment]
Confirmed on macOS 12.3.1/M1 Apple Silicon, the application crashes on launch.

**Comment by NSBum** [comment]
Using the `pip install .` process it raises and exception when attempting to install PyQt5.x and PyQt5 is known to be incompatible on Apple Silicon (ARM) architecture.

**Comment by TtlyLynzie** [comment]
same.

**Comment by zzzbra** [comment]
I can't seem to open any of the release dmgs for Mac either. I only tried the past couple minors, but the result is the same: 
<img width="263" alt="Screenshot 2023-03-15 at 23 53 04" src="https://user-images.githubusercontent.com/3282673/225510079-8f4c527c-f6da-4023-941b-bf8747951e06.png">

**Comment by 1over137** [comment]
@zzzbra 
It isn't damaged, just MacOS is trying to complain about the missing signature, which requires paying Apple for a certificate.
https://www.howtogeek.com/803598/app-is-damaged-and-cant-be-opened/
