### ISSUE TITLE
Forvo no longer sends selected word's pronunciation to my pronunciation field.

### ISSUE THREAD

**Issue by fruini** [FreeLanguageTools/vocabsieve#27]
I'm on Win11, v0.8.1 on vocabsieve.

In the screenshot below, I selected the word, vocabulary, in the sentence field and then for some reasons, I saw nothing in the pronunciation field. I did look it up on Forvo website and saw available pronunciations on a website.

![image](https://user-images.githubusercontent.com/85406813/179365157-5e001da7-5fb2-49dc-83b5-cc5766abbb59.png)

I tried restarting my computer, reinstalling the program, and making sure the Forvo (all) option is selected in configuration window, but to no avail.

**Comment by artjomsR** [comment]
Can confirm, I've previously had it working. But I've not touched my machine for a couple of days and ran VocabSieve yesterday and it doesn't grab Forvo pronunciations for me either (ie without changing anything on my end)

**Comment by 1over137** [comment]
Seems like Forvo changed their website layout a bit. I adjusted the code a bit for this and it works now. Should work again on next release.
