### ISSUE TITLE
[Feature Request] Better way to search and view the local database

### ISSUE THREAD

**Issue by abtxu** [FreeLanguageTools/vocabsieve#30]
Sorry, I am not a big fan of Anki, but exploring and viewing the saved database does not seem to be easy. I have to rely on sqlite to view the data.
It would be wonderful if better ways of exploring the data can be integrated into vocabsieve. 

Just the word-sentence pair would be good enough: search a word and show the sentence and vice versa.

**Comment by 1over137** [comment]
You can export it to a csv file, which can be opened by a spreadsheet program.

**Comment by 1over137** [comment]
This is currently out of scope of this project
