### ISSUE TITLE
App crashes often, and whenever I click configure aswell (Windows 64bit)

### ISSUE THREAD

**Issue by Adrii0121** [FreeLanguageTools/vocabsieve#35]
If I have Anki closed and try to click "configure" I get a message saying "could not reach Anki connect" (I already installed it) and if I have Anki opened it crashes inmediatly when I click "configure", I downloaded the correct version and tried uninstalling and reinstalling both the app and the add-on multiple times, but it didn't work (first time using Github, sorry if my comment uses the wrong format, let me know what I should do instead, thanks).

**Comment by 1over137** [comment]
Can you provide a few more details?
Windows version? Anki version? Latest vocabsieve release (0.8.3)?
I'm not sure what happened there. For reference, it works fine on my virtual machine with Windows 10 and Anki 2.1.51. Do you have some antivirus thing that's blocking the connection?

**Comment by Adrii0121** [comment]
I'm using Windows 10, Anki Version ⁨2.1.49 (dc80804a)⁩ and using latest Vocabsieve release. I don't think so about the Antivirus, any way to check? Just joined the TG group aswell
