### ISSUE TITLE
Provide option to disable lookup on double click (i.e. make double click behave normally)

### ISSUE THREAD

**Issue by artjomsR** [FreeLanguageTools/vocabsieve#47]
**Is your feature request related to a problem? Please describe.**
I find that default lookups with double click can be a bit slow. Instead, I rely on external translator ([QTranslate](https://quest-app.appspot.com/), DeepL etc) to translate words that are copied into the `Sentence` field. QTranslate/DeepL allows for near instantaneous translations by simply double clicking a word.

It is currently possible to use QTranslate/DeepL with VocabSieve, just cumbersome: you need to left click near a word, and then select the word using Shift / using drag select. I'd like VocabSieve not interfere with this and rely on QTranslate/DeepL for word translations. If I'd need to make a card out of the word after making a selection, I can still `Ctrl-D` immediately without changing it

**Describe the solution you'd like**
Provide a `Double click automatically seeks definitions` checkbox in settings. It's on by default. With this checkbox selected, the program behaves like it does now. With the checkbox unselected, double click behaves like it does in any other app.

**Comment by 1over137** [comment]
If you don't need the definitions, why not just use the Anki add card window?
