### ISSUE TITLE
AUR vocabsieve package installation error 

### ISSUE THREAD

**Issue by eterdas1** [FreeLanguageTools/vocabsieve#48]
While using pacman to install vocabsieve this error occurs.  

==> ERROR: A failure occurred in build().
    Aborting...
error: target not found: python-lzo
error: target not found: python-readmdict
 -> error making: python2-lzo (python-lzo)

**Comment by 1over137** [comment]
You need to use an AUR helper. python-lzo and python-readmdict are also in AUR. Also, python-lzo requires python2 to install, which you may not have in your system. I don't control that package, so I can't fix that.

**Comment by eterdas1** [comment]
![image](https://user-images.githubusercontent.com/124005286/215791656-39438584-80df-42b5-bfb8-01191efbf822.png)

I think you might have made a typo while updating it? It wont let me install because it cant find the dependency python-python-lzo.

**Comment by 1over137** [comment]
My bad. I used an automatic script to make the PKGBUILD, but I need to correct the name of python-lzo. I only edited the PKGBUILD, and forgot to make a new .SRCINFO, which is causing the problem. Should be fixed now.
