### ISSUE TITLE
Koreader Import not working

### ISSUE THREAD

**Issue by parthshahp** [FreeLanguageTools/vocabsieve#50]
**Describe the bug**

Not able to import highlights from Koreader.

**To Reproduce**
1. Click import from koreader
2. Select where the books are in your koreader

**Expected behavior**

It should go to the screen which allows me to select books to import. 

**Screenshots**

![image](https://user-images.githubusercontent.com/48393781/215937947-5c9fc3f7-b6b1-468e-a860-1963c496f611.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
- Vocabsieve version (if nightly, must be latest): 0.9.2

**Additional context**

**Comment by Ceynou** [comment]
Test the latest nighty build, I haven't yet but it should be fixed

**Comment by 1over137** [comment]
> Test the latest nighty build, I haven't yet but it should be fixed

This is unlikely to do anything for this. It seems like this user has a weird epub that is missing the stylesheet for whatever reason.

**Comment by Ceynou** [comment]
Oh my bad, for some reason I couldn't see the screenshot on my phone

**Comment by parthshahp** [comment]
I see, I think I've identified the messed up epub file, but now I'm running into a new error:

![image](https://user-images.githubusercontent.com/48393781/216051961-e12d5dbb-1034-413a-aa16-f2342abe09ff.png)

**Comment by 1over137** [comment]
Oh, seems like it can't deal with Chinese because the sentence splitter doesn't work with it. 
I'm planning to retire this highlight import method some time later as it is rather unreliable. Please consider switching to using vocabulary builder in KOReader (check settings, you need to turn on context, turn off auto-adding).

**Comment by 1over137** [comment]
Also, it should now just return the whole segment if the sentence splitter doesn't work.
