### ISSUE TITLE
Ancient greek support

### ISSUE THREAD

**Issue by dezukaful** [FreeLanguageTools/vocabsieve#55]
It would be great to have Ancient greek as its not available in the list of languages even though it is already in Wiktionary

**Comment by wagewarsgetrichdiegoncharov** [comment]
I haven't tested this, but you might be able to add it by opening up lemmatizer.py and adding 'grc' to the list of language codes. Apologies if this doesn't work - I'm not a programmer, but I've fiddled with vocabsieve a little for my own usage.
