### ISSUE TITLE
Target word is not shown in “bold type” on Anki

### ISSUE THREAD

**Issue by Exponent4806** [FreeLanguageTools/vocabsieve#56]
VocabSieve often fails to "bold" words correctly.  Instead of showing the target word in "bold type", the word is shown with 2 asterisks:

![grafik](https://user-images.githubusercontent.com/121114125/228747965-3cf9e7a9-230e-4066-9bae-bfc45ceb5902.png)

**To Reproduce**
1. Use latest AppImage on Manjaro Linux
2. Choose a sentence and double click to bold the target word.
3. Sometimes, the words are not shown correctly on Anki (5% of words).

I have tried to find a reproducible pattern, but I have been unable to do so. 

Most of the time the “bolding process” works correctly but othertimes it fails.

**Expected behavior**
Every word should appear in bold type.

**Desktop:**
 - OS: Manjaro KDE Stable (latest)
 - AppImage

![grafik](https://user-images.githubusercontent.com/121114125/228748689-addcfe20-e6f8-4614-a422-3e5e2344f936.png)

**Comment by Memory383** [comment]
I will collect here some words in German that are not "bolded" correctly in VocabSieve. 

A proper list of words might be useful for debugging.

**Gilde** 
![grafik](https://user-images.githubusercontent.com/121114125/228753379-af3a9401-f19a-41eb-84d3-c49ec320733b.png)

**Comment by 1over137** [comment]
This is strange, but I can't seem to reproduce it. I assume this has to do with some quirks of the text bolding method. Maybe I should just remove it and force using underscores.

Can you tell me:
- Is your bolding set to font weight or underscores?
- This is from the importer or the interactive card creation method?

**Comment by Memory383** [comment]
> Is your bolding set to font weight or underscores?
Font weight

> This is from the importer or the interactive card creation method?
 interactive card creation method

I do not know if the bug can be reproduced when changing to "underscores". I will try itand let you know later...

The bug is hard to reproduce consistently. Sometimes I even try the same sentence and it does not always appears. Strange. For example: 

![grafik](https://user-images.githubusercontent.com/121114125/233841192-e9fd0aef-fd62-4e50-a160-d2e8366461eb.png)

I tried reproducing the bug with the same sentence in the above card and the software worked correctly.

**Comment by 1over137** [comment]
Check if this is reproducible on the latest version. The bolding code has been changed somewhat.

**Comment by Exponent4806** [comment]
> Check if this is reproducible on the latest version. The bolding code has been changed somewhat.

The issue is still present.

![image](https://github.com/FreeLanguageTools/vocabsieve/assets/121114125/49142279-fede-438f-9f19-e549892cdb24)

_"Fitnesstracker registrieren Herzfrequenz und Schrittzahl, die sich durch eine
abgefeimte Anreizstrategie – etwa durch Bonifikationen für getane Schritte – **justieren
lässt."_

Let's keep this issue open....

**Comment by Exponent4806** [comment]
The issue seems to apper only with the option "font weight" turned on.

When the bolding is done via "underscores" the issue is not reproduced. 

The problem is elusive. It is even difficult to reproduce sometimes, but I guess that around 10% of my cards in German have this problem.

**Comment by 1over137** [comment]
Font weight has been removed in 0.12.0 to simplify the logic.
