### ISSUE TITLE
Error: Operation Error("unable to open database file")

### ISSUE THREAD

**Issue by mynamesjb** [FreeLanguageTools/vocabsieve#58]
When I go to Import > Kindle Lookups then navigate to my Kindle at E:\system\vocabulary, I receive the error given above.

I am unable to see the file through file explorer, but can find it if I put the address in full. Kindle Mate has been able to sync and import the vocabulary without issue. I have also been able to use this https://henrywang.nl/kindle-vocabulary-builder-export-for-free/. The problem only happens on Vocabsieve.

**Desktop (please complete the following information):**
 - OS:  Windows 10 Pro Version	10.0.19044 Build 19044
- Vocabsieve version 0.10.1

**Comment by 1over137** [comment]
You should navigate to your Kindle root directory, not the directory directly containing vocab.db. Does it happen if you do that?
