### ISSUE TITLE
Hebrew missing from dropdown, but seems to be supported in code

### ISSUE THREAD

**Issue by zsilver1** [FreeLanguageTools/vocabsieve#59]
**Describe the bug**

Language selection dropdown is missing Hebrew. The code for Hebrew is present in code, so not sure why it can't be selected.

**To Reproduce**
1. Go to 'Configure..'
2. Click on 'Target Language'
3. Hebrew is missing

**Expected behavior**
Hebrew should be present, since its language abbreviation exists in code.

**Screenshots**
<img width="207" alt="Screenshot" src="https://user-images.githubusercontent.com/12775745/234618775-7638f8d5-0498-4ec0-8a72-ba07a9de4173.png">

**Desktop (please complete the following information):**
 - OS: MacOS (M2)
- Vocabsieve version (if nightly, must be latest): 0.10.1

**Comment by 1over137** [comment]
Google translate wants code "iw" instead, I patched the function for this, so it should work now.
