### ISSUE TITLE
Problem opening v0.10.0, v0.10.1 on Monterey 12.4

### ISSUE THREAD

**Issue by wagewarsgetrichdiegoncharov** [FreeLanguageTools/vocabsieve#66]
I'm unable to open any version after v.0.8.3 on my Mac. v0.8.3 is working and installs and runs normally. The install on any later version happens normally, and then I get the below error when opening the application: 

<img width="266" alt="Screen Shot 2023-06-06 at 3 31 10 PM" src="https://github.com/FreeLanguageTools/vocabsieve/assets/119229686/35ead69d-7d62-4bf4-8560-ce83a3895971">

 - OS: Mac OS Monterey 12.4
- Vocabsieve version (if nightly, must be latest): v0.10.0, v0.10.1 mac os

**Comment by wagewarsgetrichdiegoncharov** [comment]
Update: I ran the following in terminal and was able to open vocabsieve normally! 

xattr -d com.apple.quarantine /Applications/VocabSieve-v0.10.1-macos.app

**Comment by cole-h** [comment]
Another method I just tried that worked for me was to run `chmod -R 755 /path/to/the/.app` and then `xattr -cr /path/to/the/.app` and it worked for me after that.

**Comment by wagewarsgetrichdiegoncharov** [comment]
After getting it to work by taking it out of quarantine, I ended up running into more issues with the app refusing to translate any word in a sentence that had non-standard-to-English characters (č etc.) ... @cole-h I tried your solution, and the app did open, but I'm still getting this new bug. I'm running the app successfully through Python currently.

**Comment by 1over137** [comment]
Closing this as the original issue is resolved. Open a new issue if you are still encountering problems.
