### ISSUE TITLE
List of Cram Words When Analyzing Book

### ISSUE THREAD

**Issue by wagewarsgetrichdiegoncharov** [FreeLanguageTools/vocabsieve#67]
I love the Analyze feature. It would be really helpful for me if, after scanning the book, VocabSieve was able to spit out the, say, 100 most-common unknown lemmas so that I can memorize those before attempting to read the book. 

It seems like that's probably data that's already being calculated, and it just needs to be printed somewhere.

**Comment by 1over137** [comment]
Sure, this is planned, but wasn't implemented yet because of the ever expanding scope involved in the tool. I guess a simple widget displaying the words in order would be good enough? I also considered implementing a feature to just automatically create them as Anki notes.

**Comment by wagewarsgetrichdiegoncharov** [comment]
Of course, makes sense! There's so many possible features for this tool. And, vocabsieve is a really great program that I'm finding so useful. 

A widget displaying all the unknown words in order would totally work, or even better, sorted by frequency! Automatic Anki notes would also be neat.

**Comment by 1over137** [comment]
Now implemented as an importer, you can directly add them to Anki
![20240109-165703](https://github.com/FreeLanguageTools/vocabsieve/assets/22680475/01d49811-9b8e-402a-9c78-22864d207ec1)
