### ISSUE TITLE
Wayland expected behaviour

### ISSUE THREAD

**Issue by Haze-sh** [FreeLanguageTools/vocabsieve#69]
**Describe the bug**
I have to click Ctrl-V or Read clipboard button for mining the sentence where I believe this could be automatic?
The window is focused on vocabsieve while the clipboard is being populated by words from another program.

**Expected behavior**
Automatic word mining without clicking the Read clipboard button.

**Comment by 1over137** [comment]
Unfortunately I think there is no way to monitor the clipboard in Wayland, unless there is some other API offered by your desktop environment, which Qt likely doesn't support anyway. The workaround for this implemented now is that we check the clipboard content everytime focus returns to the window, which wouldn't happen if the focused stayed on the window the whole time. Maybe I'll add a polling function for this use case.

**Comment by Vilhelm-Ian** [comment]
@1over137 there is with wl-paste watch

**Comment by 1over137** [comment]
Polling is already implemented now, so I'll be closing this.
