### ISSUE TITLE
Feature suggestion: Modular/Extensible Definition Lookup

### ISSUE THREAD

**Issue by spirited1086** [FreeLanguageTools/vocabsieve#72]
Right now Vocabsieve has its own internal look up, e.g., using free wikitionary definition or by importing comptaible JSON dictionary files. But if there was a way to make it extensible so that people could simply add their own python scripts it would be infinitely better. 

For every language there are tons of open source scripts/apps that offer the ability to extract definitions or other information from very specific dictionaries. E.g., I like "spanishdict.com" and there are many pre-exsiting scripts that extract defintions from that site. And then one could add regex modifications to those scripts to format the text perfectly for anki.

In this case, vocabsieve wouldn't need to worry about extending its lookup feature, that could be up to individual projects that simply use code from pre-existing lookup programs.

**Comment by 1over137** [comment]
There is this plan to revamp the whole system of handling dictionary definitions. The current way it's being handled is rather hacky and not extensible, as it hard codes two slots for definitions and can't dynamically show definitions in a preferred order based on availability. The idea is it should be reorganized on a list, and the two boxes on the window will be filled by priority order based on availability of definitions, so you can use all dictionaries at the same time. Unfortunately lately I didn't have time to do much for this project. Maybe in the coming months I will have time to do this.

**Comment by 1over137** [comment]
The definition lookup system is now handled in a more extensible way, though there is still no way for end users to directly create new sources. Maybe I can provide a way for it to run an external script, but I'm not sure that's going to work well at all on frozen versions (macos and windows).

**Comment by 1over137** [comment]
Honestly, I'm not quite sure there is a need for extensible lookup systems based on user scripts. There currently just isn't that many users, and anything reasonably useful can be upstreamed since it is now relatively easy to extend the dictionary system. It seems to add a lot of complexity and would be difficult to debug if anything went wrong.
