### ISSUE TITLE
Android devices cannot be selected for KOReader import

### ISSUE THREAD

**Issue by LesbiansAttack** [FreeLanguageTools/vocabsieve#79]
**Describe the bug**
When the file dialog appears for selecting the directory for KOReader, android devices will not show up ex:
![image](https://github.com/FreeLanguageTools/vocabsieve/assets/112827749/d8f85910-4014-4e9c-a561-3fd4df691c3b)
(Left is my file browser, right is the dialog window from vocabsieve)

**To Reproduce**
1. plug in android device
2. open vocabsieve
3. select 'KOReader VocabBuilder Import'
4. try to select the android device for import

**Expected behavior**
Being able to select an android device's storage, which contains the KOReader folder along with the epubs.

**Desktop (please complete the following information):**
 - OS: Windows 11
- Vocabsieve version (if nightly, must be latest): 0.10.1

**Additional context**
I believe this has to do with android no longer mounting the same way it used to. The whole device seems to be in read-only mode. The only work-around I've found is to copy my *entire devices directory* and then paste it onto my system, and select that. That seems unnecessary.

**Comment by 1over137** [comment]
VocabSieve uses the system's native file chooser dialog. There is no way to control what shows up and what doesn't, so I can't help with this. For Android I would suggest using something like Syncthing to synchronize your folder with ebooks and KOReader settings. This way you also get the benefit of being able to synchronize books to the device wirelessly.
