### ISSUE TITLE
Lingva.ml is down, so translations are not available via Google Translate dictionary now.

### ISSUE THREAD

**Issue by Vedaukr** [FreeLanguageTools/vocabsieve#81]
Looks like [lingva.ml](https://lingva.ml/) is being down for a while now (reddit [post](https://www.reddit.com/r/degoogle/comments/155i3yu/lingva_translate_is_down/)). 
Does anyone know any open-source alternatives/suggestions?

**Comment by 1over137** [comment]
You can change to another instance in Configure>Network. The feature is designed with the ability to use a different instance to begin with.
That said it seems that lingva.ml seems to be having issues with their domains. I'm changing the default settings to use https://lingva.lunar.icu/. Existing users will have to change the settings themselves and use one of the working instances listed on their README at https://github.com/thedaviddelta/lingva-translate.
