### ISSUE TITLE
Add a hand made definition even if no definition is found

### ISSUE THREAD

**Issue by Mycheze** [FreeLanguageTools/vocabsieve#84]
**Describe the bug**
If the internal dictionary can't find a definition, you can't manually add the note, even if you create your own definition.

**To Reproduce**
1. Look up a word (which fails to find a definition)
2. Edit the definition
3. Cannot add definition
If you then copy the sentence and click over into a new window, it sometimes allows a note to be added.

**Expected behavior**
I would like to be able to override and add my own definition. Ideally, it also saves that definition somewhere and can access it later.

**Screenshots**
The difference between these is just copying the sentence and changing window focus. In the first pic, you can't add the card. But in the second, you can for some reason.
![image](https://github.com/FreeLanguageTools/vocabsieve/assets/71797685/d3ab6578-7890-4eab-81b1-9786ea6df96a)
![image](https://github.com/FreeLanguageTools/vocabsieve/assets/71797685/a23c39ef-b1a7-473a-90e4-cff70c759437)

**Desktop (please complete the following information):**
 - OS: Pop!_OS
- Vocabsieve version (if nightly, must be latest): v0.10.1

**Additional context**
If there was an "override definition" button, that would be amazing. What it would do is:
1. Allow whatever to be added with Ctrl + S (ungreying out the box)
2. Replace the definition box with a standard "template" to be filled in
3. Freeze clipboard monitoring for a moment (so that you can copy and paste from something else without messing up the sentence)
4. Save that headword/child word/definition somewhere so that the word can be looked up in the future.

**Comment by 1over137** [comment]
https://github.com/FreeLanguageTools/vocabsieve/issues/77
Someone already reported it before and the new version should be able to do what you want.
