### ISSUE TITLE
Certain words with capital letters don't get parsed

### ISSUE THREAD

**Issue by Mycheze** [FreeLanguageTools/vocabsieve#85]
**Describe the bug**
Certain words with capital letters don't get properly lowercased when searching the dictionary.

**To Reproduce**
1. Search "Právě" (or many other words) in Czech (cs). No result found.
2. Search "právě" (or many other words) in Czech (cs).

**Expected behavior**
The tool should find the definition for either capital or lowercase words.

**Screenshots**
![image](https://github.com/FreeLanguageTools/vocabsieve/assets/71797685/4345cff3-a00a-4086-80ba-9b57059cca7c)
![image](https://github.com/FreeLanguageTools/vocabsieve/assets/71797685/12f0f6ca-4458-4129-bf79-cd998f62d760)

**Desktop (please complete the following information):**
 - OS: Pop!_OS
- Vocabsieve version (if nightly, must be latest): v0.10.1

**Comment by 1over137** [comment]
Good catch! So as I found out the cause of this is that I had assumed simplemma would turn all words lowercase, so I had the word looked up both in the processed form and the capitalized form. Apparently it doesn't actually do that in some languages. This should be easily fixed.
