### ISSUE TITLE
Clear image option

### ISSUE THREAD

**Issue by Mycheze** [FreeLanguageTools/vocabsieve#86]
**Is your feature request related to a problem? Please describe.**
I frequently take screenshots of things on my computer that I don't want to be part of my Anki cards. But if I take a screenshot with Vocabsieve open, I need to close and reopen the program just to get rid of the screenshot. 

**Describe the solution you'd like**
A little X in the top right of the image window would be perfect. Then it just forgets that image.

**Comment by 1over137** [comment]
Someone actually implemented this already #54. You can clear the image by using Ctrl-I though I guess it is undocumented and completely hidden. I should put some hints about it and possibly add a small red x button.
