### ISSUE TITLE
Update instructions would be very helpful

### ISSUE THREAD

**Issue by Mycheze** [FreeLanguageTools/vocabsieve#88]
**Is your feature request related to a problem? Please describe.**
Every single time there's an update, I completely forget how to update the program. I always try things that I think will work, but they never do and I end up having to ask directly.

**Describe the solution you'd like**
A wiki page or part of the readme that has simple update instructions for various systems (and then link that page in the update reminder).

**Additional context**
Personally, I'm on an Ubuntu like system and I *think* I installed with pip3, but I can't figure out how to update it. The Appimage just opened the last version and I couldn't get anything to update with pip3.

**Comment by 1over137** [comment]
This AppImage issue is weird. I have no idea why it happens.
The command to install with pip3 is also the command to update. What problems are you encountering?

**Comment by Mycheze** [comment]
I was just encountering the problem that using "install" is unintuitive. I was trying with "update" and "upgrade," which is why it didn't work. Just a short "To update, use this command: " for normies would be nice :sweat_smile:
