### ISSUE TITLE
[Bug] Settings are not remembered

### ISSUE THREAD

**Issue by GPLv3-fan** [FreeLanguageTools/vocabsieve#9]
Vocabsieve does not remember the settings on Manjaro KDE (latest stable).

**Steps to reproduce:**
1) Import 2 stardict dictionaries
2) Choose them to Definition 1 and 2 fields

![image](https://user-images.githubusercontent.com/58692066/163626930-b989cb43-e28f-488a-9c44-67fdd9a772d8.png)

After restarting Vocabsieve, the default settings appear and users have to choose again the dictionaries that they want:

![image](https://user-images.githubusercontent.com/58692066/163626995-5aaed448-1020-4925-a56a-8350632342c9.png)

This seems a regression. The problem was not present on Version 0.6

**Comment by 1over137** [comment]
Oh. The configuration system has been mostly rewritten for this release, even though the interface did not change much.
So there seems to be an execution order problem here. I will try to fix this asap. 
In the mean time, the settings are actually saved. It's just that it gets overwritten if you use custom dictionaries when you open the config window. If you set the dictionaries, they should work until you open the config window the next time.
Sorry for the oversight.

**Comment by GPLv3-fan** [comment]
The issue was solved in the new release :D  Thank you so much !
