### ISSUE TITLE
Gender support

### ISSUE THREAD

**Issue by RasmusRendal** [FreeLanguageTools/vocabsieve#94]
**Is your feature request related to a problem? Please describe.**
Several human languages regrettably include grammatical gender in their grammar. For these languages, when using Vocabsieve, I will learn many words without learning their grammatical gender.

**Describe the solution you'd like**
The Anki cards generated by Vocabsieve for nouns should have the word on the back of the card coloured according to some gender colouring scheme. For instance, German seems to have widely accepted red for feminine, blue for masculine, and green for neuter.

The colour approach seems to be accepted in the language learning community, amongst other places being advocated in the book Fluent Forever. It allows one to recognize the gender quicker, than if one simply used the first letter (f, m, n).

![image](https://github.com/FreeLanguageTools/vocabsieve/assets/19538856/767d24e2-6385-47dd-b898-3ea5e3f14ba5)

**Comment by 1over137** [comment]
I would generally prefer to avoid integrating language-specific features into VocabSieve. My preferred solution would be to possibly add language specific handling of Wiktionary definitions so it is included there. The wiktionary parsing code is one of the oldest part of the codebase and is due for an upgrade anyways. It should just indicate it next to the *Noun* line.

**Comment by Exponent4806** [comment]
> German seems to have widely accepted red for feminine, blue for masculine, and green for neuter.

There is an easy solution to this issue. I have paid to one of the best developers of Anki to solve this problem.

Steps:
1) Install the add-on:
[ZIM Reader - Look up words in Wiktionary](https://ankiweb.net/shared/info/951350249)

2) Download the German Wiktionary in .zim format (full version):
https://wiki.kiwix.org/wiki/Content_in_all_languages

3) Create a field in your card template only to add the grammatical gender.

3) With the .zim file of the German Wiktionary and the add-on you can add the gender to each card:

![image](https://github.com/FreeLanguageTools/vocabsieve/assets/121114125/53f4bd38-5e71-4630-8cf0-f5e285426238)

5) Finally, edit the styling of your card to change the background of the cards according to the gender:
masculine= blue
feminine= pink
neuter= green

Here is an deck as an example. You can copy the .css :  
[Selected Notes -german nouns- colors.zip](https://github.com/FreeLanguageTools/vocabsieve/files/13471297/Selected.Notes.-german.nouns-.colors.zip)

Examples:
![image](https://github.com/FreeLanguageTools/vocabsieve/assets/121114125/07d52a62-ba3b-441e-80bf-3906e7a83755)

![image](https://github.com/FreeLanguageTools/vocabsieve/assets/121114125/e0763b1c-70ef-4a1f-ae56-47916aeb43e8)

![image](https://github.com/FreeLanguageTools/vocabsieve/assets/121114125/f06067e2-66ca-4dc5-bf21-9b0a6ed3958a)
![image](https://github.com/FreeLanguageTools/vocabsieve/assets/121114125/da301723-8549-47f7-8bae-cff079afa807)
